<?php

include(ROOT_PATH . '/app/views/layouts/layout.phtml');

echo '<h1 class="text-center text-3xl">EL TODO</h1>';



?>
<div class="flex">
  <div class="w-1/3">w-1/3</div>
  <div class="w-1/3">w-1/3</div>
  <div class="w-1/3">w-1/3</div>

</div>


    <form action="#" method="post">
<div class="form">
<div class="dalt">

    <div class="part">
        <label>
            text<span class="req"></span>
        </label>
        <input type="text" name="text" id="text" required />
    </div>
    <div class="part">
        <label>
        name_user<span class="req"></span>
        </label>
        <input type="text" name="name_user" id="name_user" required />
    </div>
   
<button type="submit" name="boto-summit" class="button button-block">Afegir</button>
</div>
</form>





<?php
$file = file_get_contents("data.json");
$data = json_decode($file, true);
$time_actual = time();
$data[] = array(
    
    'text'           => $_POST["text"],
    "time_start"     => $time_actual,
    "time_finish"    => "",
    "name_user"      => $_POST["name_user"]
);

file_put_contents('data.json',json_encode($data), LOCK_EX);



    include(ROOT_PATH . '/app/views/layouts/footer.phtml');
?>